[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "https://andrewraj.netlify.com/*"
  to = "https://www.andrewraj.com/"
  status = 301
  force = true
  conditions = {Language = ["en","es"], Country = ["US"]}